insert into courses (code, name) values ('HMK-100', 'Zieme LLC');
insert into courses (code, name) values ('VKS-614', 'Stracke and Sons');
insert into courses (code, name) values ('WEL-344', 'Kub, Quitzon and Hayes');
insert into courses (code, name) values ('ALL-322', 'Sanford, Rowe and Klein');
insert into courses (code, name) values ('FTD-980', 'Ryan, Schroeder and Langosh');
insert into courses (code, name) values ('KFA-876', 'Haag, Casper and Anderson');
insert into courses (code, name) values ('KUE-577', 'Dickens LLC');
insert into courses (code, name) values ('YGW-577', 'Glover-Murazik');
insert into courses (code, name) values ('SYM-819', 'Turcotte Group');
insert into courses (code, name) values ('DXZ-891', 'Gusikowski Group');
insert into courses (code, name) values ('SFB-709', 'Christiansen, Keeling and Flatley');
insert into courses (code, name) values ('UZW-396', 'Gutkowski-Wolf');
insert into courses (code, name) values ('UHC-641', 'Stoltenberg, Oberbrunner and Bode');
insert into courses (code, name) values ('AVF-847', 'Huels-Batz');
insert into courses (code, name) values ('RXC-897', 'Walter Group');
insert into courses (code, name) values ('FPX-387', 'Lynch, Romaguera and Yost');
insert into courses (code, name) values ('TKF-516', 'Wilkinson and Sons');
insert into courses (code, name) values ('VCY-763', 'Zieme, Dicki and Sipes');
insert into courses (code, name) values ('OAF-357', 'Collier, Jerde and Erdman');
insert into courses (code, name) values ('ZNP-477', 'Klocko Group');
insert into courses (code, name) values ('GWW-828', 'Ebert-Hayes');
insert into courses (code, name) values ('OXE-668', 'Schmitt-Gerlach');
insert into courses (code, name) values ('HKD-341', 'Miller-Koelpin');
insert into courses (code, name) values ('LFM-510', 'Cassin-Ratke');
insert into courses (code, name) values ('FQE-516', 'Marks, Kozey and Kling');
insert into courses (code, name) values ('QWP-310', 'Zboncak Inc');
insert into courses (code, name) values ('NZK-185', 'McLaughlin, Hyatt and Hamill');
insert into courses (code, name) values ('KRX-835', 'Terry, Paucek and Senger');
insert into courses (code, name) values ('WLU-672', 'Schultz-Gutmann');
insert into courses (code, name) values ('QWG-476', 'Hartmann Group');
insert into courses (code, name) values ('DEB-036', 'Hamill LLC');
insert into courses (code, name) values ('DVF-053', 'Senger-Fahey');
insert into courses (code, name) values ('OQW-691', 'Schuppe-Jenkins');
insert into courses (code, name) values ('UNR-776', 'Morar, Kuhlman and Aufderhar');
insert into courses (code, name) values ('MFQ-847', 'Carroll-Johnston');
insert into courses (code, name) values ('OPV-089', 'Brown LLC');
insert into courses (code, name) values ('HKW-103', 'Stokes and Sons');
insert into courses (code, name) values ('PCX-066', 'Hilpert LLC');
insert into courses (code, name) values ('GJA-440', 'Brekke, Langosh and Casper');
insert into courses (code, name) values ('WRB-021', 'Schroeder-Bauch');
insert into courses (code, name) values ('ZDP-617', 'Kreiger-Stanton');
insert into courses (code, name) values ('CDY-085', 'Goyette LLC');
insert into courses (code, name) values ('YBZ-769', 'Ritchie-Sanford');
insert into courses (code, name) values ('AOR-467', 'Bosco Inc');
insert into courses (code, name) values ('EAF-378', 'Wuckert, Tillman and Rempel');
insert into courses (code, name) values ('XUD-125', 'Strosin and Sons');
insert into courses (code, name) values ('TPG-158', 'Goyette-Tromp');
insert into courses (code, name) values ('FZV-282', 'Wuckert-Kirlin');
insert into courses (code, name) values ('HBH-681', 'Christiansen, Thompson and Heidenreich');
insert into courses (code, name) values ('UGR-014', 'McLaughlin-Ortiz');
insert into courses (code, name) values ('HHZ-045', 'Bogisich Inc');
insert into courses (code, name) values ('MXO-492', 'Kemmer, O''Conner and Wisozk');
insert into courses (code, name) values ('BYI-186', 'Morissette-Wehner');
insert into courses (code, name) values ('BVN-346', 'Rutherford-Bergstrom');
insert into courses (code, name) values ('UMV-485', 'Durgan, Hand and O''Conner');
insert into courses (code, name) values ('FTP-570', 'Wolf Inc');
insert into courses (code, name) values ('XFS-623', 'Parker-Batz');
insert into courses (code, name) values ('BIL-372', 'Kemmer-Kerluke');
insert into courses (code, name) values ('VBX-861', 'Goyette Inc');
insert into courses (code, name) values ('DGQ-593', 'Nitzsche-Ortiz');
insert into courses (code, name) values ('OIU-900', 'Will, Ritchie and Jones');
insert into courses (code, name) values ('LXU-361', 'Abshire-Bednar');
insert into courses (code, name) values ('SFD-196', 'Jaskolski-Hermann');
insert into courses (code, name) values ('TPV-634', 'Auer-Gerlach');
insert into courses (code, name) values ('SKT-698', 'Weissnat-Connelly');
insert into courses (code, name) values ('MVK-577', 'Kerluke-McClure');
insert into courses (code, name) values ('DFK-647', 'Rogahn LLC');
insert into courses (code, name) values ('RBW-356', 'MacGyver-Littel');
insert into courses (code, name) values ('BXF-430', 'Harris Inc');
insert into courses (code, name) values ('GBG-091', 'Quitzon, Beer and Hamill');
insert into courses (code, name) values ('FQO-234', 'Anderson-Ritchie');
insert into courses (code, name) values ('FUG-686', 'Hirthe-Walsh');
insert into courses (code, name) values ('MKX-566', 'Terry, Ritchie and Mante');
insert into courses (code, name) values ('OZU-345', 'Bartoletti Inc');
insert into courses (code, name) values ('HOW-902', 'Dickinson-DuBuque');
insert into courses (code, name) values ('DRW-215', 'Johnston LLC');
insert into courses (code, name) values ('VYP-884', 'Howe, Reynolds and Langosh');
insert into courses (code, name) values ('JKZ-094', 'Steuber LLC');
insert into courses (code, name) values ('OTD-905', 'Jacobi and Sons');
insert into courses (code, name) values ('XON-066', 'Medhurst and Sons');
insert into courses (code, name) values ('CSR-766', 'DuBuque-Conroy');
insert into courses (code, name) values ('MNH-432', 'Wolff Group');
insert into courses (code, name) values ('QVL-138', 'Mann, Harvey and Wehner');
insert into courses (code, name) values ('GYQ-428', 'Schumm-Brown');
insert into courses (code, name) values ('NEQ-536', 'Kozey-Little');
insert into courses (code, name) values ('CDU-744', 'Gibson-Wiza');
insert into courses (code, name) values ('TYW-925', 'Hoeger-Heathcote');
insert into courses (code, name) values ('GUM-074', 'Schaden LLC');
insert into courses (code, name) values ('PDH-450', 'Abernathy and Sons');
insert into courses (code, name) values ('MLJ-306', 'Barrows, Kemmer and Anderson');
insert into courses (code, name) values ('HZR-665', 'Klocko, Little and DuBuque');
insert into courses (code, name) values ('OVU-248', 'Block-Gleichner');
insert into courses (code, name) values ('UDL-708', 'Watsica-Witting');
insert into courses (code, name) values ('OHH-416', 'Crona LLC');
insert into courses (code, name) values ('DJC-963', 'Pagac, Mann and Toy');
insert into courses (code, name) values ('JDA-939', 'Powlowski Group');
insert into courses (code, name) values ('UXX-904', 'Runolfsson-Mills');
insert into courses (code, name) values ('SEZ-518', 'Heidenreich, Muller and Collier');
insert into courses (code, name) values ('ZCE-407', 'Dach, Wintheiser and Doyle');
insert into courses (code, name) values ('ZDW-190', 'Quigley, D''Amore and Becker');
insert into courses (code, name) values ('RNL-279', 'Ankunding, Vandervort and Ziemann');
insert into courses (code, name) values ('IEJ-159', 'Lindgren, Bode and Wilderman');
insert into courses (code, name) values ('HRM-482', 'Roob, Quigley and Feil');
insert into courses (code, name) values ('NRK-129', 'Aufderhar-Langworth');
insert into courses (code, name) values ('GOQ-351', 'Stracke, Cassin and Senger');
insert into courses (code, name) values ('XKV-477', 'Reichel, Raynor and Labadie');
insert into courses (code, name) values ('RZM-634', 'Wolf, Ferry and Metz');
insert into courses (code, name) values ('MOQ-100', 'Murray, Schulist and Schimmel');
insert into courses (code, name) values ('WIX-090', 'Sipes and Sons');
insert into courses (code, name) values ('BLS-574', 'Murazik-Lind');
insert into courses (code, name) values ('TYV-733', 'Grimes, Schulist and D''Amore');
insert into courses (code, name) values ('NOM-307', 'Dooley-Runolfsdottir');
insert into courses (code, name) values ('HBK-443', 'Halvorson-Russel');
insert into courses (code, name) values ('JKO-139', 'Langworth and Sons');
insert into courses (code, name) values ('QWD-305', 'Schulist and Sons');
insert into courses (code, name) values ('CBX-113', 'Zboncak and Sons');
insert into courses (code, name) values ('XGM-436', 'Homenick, Schamberger and Gislason');
insert into courses (code, name) values ('PFZ-728', 'Altenwerth-Weber');
insert into courses (code, name) values ('QMS-430', 'Jenkins-Braun');
insert into courses (code, name) values ('XJS-242', 'Streich and Sons');
insert into courses (code, name) values ('MYO-458', 'Barrows Inc');
insert into courses (code, name) values ('VHJ-893', 'Volkman Group');
insert into courses (code, name) values ('JSK-967', 'Hahn Inc');
insert into courses (code, name) values ('DML-292', 'Lueilwitz-Upton');
insert into courses (code, name) values ('MSB-829', 'Fisher-Rogahn');
insert into courses (code, name) values ('SUL-272', 'Wilkinson-Marvin');
insert into courses (code, name) values ('IAP-779', 'Lockman-Schowalter');
insert into courses (code, name) values ('CIK-531', 'Goodwin-Denesik');
insert into courses (code, name) values ('SHV-793', 'Williamson-Green');
insert into courses (code, name) values ('KYF-662', 'Windler LLC');
insert into courses (code, name) values ('OZB-975', 'Goodwin-Robel');
insert into courses (code, name) values ('AKU-599', 'Murray, Prosacco and McDermott');
insert into courses (code, name) values ('SSX-303', 'Schultz, Kilback and Schroeder');
insert into courses (code, name) values ('ETN-014', 'Tromp, Beatty and Keebler');
insert into courses (code, name) values ('KRQ-209', 'Moore, Feest and Rosenbaum');
insert into courses (code, name) values ('GVA-850', 'Lubowitz, Bergstrom and Okuneva');
insert into courses (code, name) values ('CEU-502', 'Walker, Kautzer and Ruecker');
insert into courses (code, name) values ('QFH-630', 'Brakus LLC');
insert into courses (code, name) values ('HBU-423', 'Koepp, Tremblay and Turcotte');
insert into courses (code, name) values ('EHE-729', 'Lesch Inc');
insert into courses (code, name) values ('ESX-830', 'Gulgowski-Lemke');
insert into courses (code, name) values ('MPQ-557', 'Connelly Inc');
insert into courses (code, name) values ('TLE-779', 'Nitzsche, Jenkins and Carter');
insert into courses (code, name) values ('ADU-329', 'Pagac, Welch and Ernser');
insert into courses (code, name) values ('UUZ-367', 'Erdman Group');
insert into courses (code, name) values ('BTC-964', 'Denesik-Rohan');
insert into courses (code, name) values ('KVR-796', 'Cronin LLC');
insert into courses (code, name) values ('YYF-691', 'Lowe-Rath');
insert into courses (code, name) values ('RWT-502', 'Fisher LLC');
insert into courses (code, name) values ('BPM-015', 'Hudson, Sipes and Dooley');
insert into courses (code, name) values ('UYQ-150', 'Doyle, Schuster and Wilderman');
insert into courses (code, name) values ('VZD-869', 'Pacocha, Johnston and Deckow');
insert into courses (code, name) values ('OSR-076', 'Dach, Durgan and Paucek');
insert into courses (code, name) values ('FYL-801', 'Mohr, McKenzie and Hayes');
insert into courses (code, name) values ('GDO-490', 'Runolfsdottir Group');
insert into courses (code, name) values ('KOH-128', 'Nolan, Wyman and Klocko');
insert into courses (code, name) values ('MTI-184', 'Tillman-Johns');
insert into courses (code, name) values ('CXK-545', 'Graham-Wilkinson');
insert into courses (code, name) values ('JLW-339', 'Berge, Kertzmann and Mante');
insert into courses (code, name) values ('UYT-966', 'Kautzer-Bogan');
insert into courses (code, name) values ('BDR-883', 'Shields and Sons');
insert into courses (code, name) values ('SEZ-979', 'Crist-Quitzon');
insert into courses (code, name) values ('VHT-380', 'Welch-Gutmann');
insert into courses (code, name) values ('DQA-284', 'Kreiger, Mann and Legros');
insert into courses (code, name) values ('NYJ-923', 'Leffler Group');
insert into courses (code, name) values ('OSN-214', 'Labadie-Dickens');
insert into courses (code, name) values ('DRJ-737', 'Schmidt, Padberg and Dietrich');
insert into courses (code, name) values ('TNT-633', 'Barrows-Hegmann');
insert into courses (code, name) values ('SHL-897', 'Marks Group');
insert into courses (code, name) values ('QWE-586', 'Renner Inc');
insert into courses (code, name) values ('IIT-754', 'Schinner, Murazik and Lakin');
insert into courses (code, name) values ('UGS-429', 'Glover Group');
insert into courses (code, name) values ('MEH-989', 'Auer Group');
insert into courses (code, name) values ('TSP-733', 'Glover-Veum');
insert into courses (code, name) values ('YHB-830', 'Rice, Brown and Kovacek');
insert into courses (code, name) values ('RMZ-983', 'Dietrich-Jones');
insert into courses (code, name) values ('PRM-801', 'Yundt, Hudson and Gorczany');
insert into courses (code, name) values ('XTK-117', 'Rutherford-Hartmann');
insert into courses (code, name) values ('HRR-615', 'Langworth, Heaney and Stark');
insert into courses (code, name) values ('SAK-377', 'Hilpert-Orn');
insert into courses (code, name) values ('CQS-976', 'Ebert-Kunze');
insert into courses (code, name) values ('TNI-332', 'Hermann Inc');
insert into courses (code, name) values ('NOX-171', 'Feest Group');
insert into courses (code, name) values ('HNN-784', 'Jerde Inc');
insert into courses (code, name) values ('WQR-495', 'Oberbrunner, Kling and Gulgowski');
insert into courses (code, name) values ('AIE-306', 'Ebert, Weimann and Abbott');
insert into courses (code, name) values ('KAB-617', 'Turcotte-Smitham');
insert into courses (code, name) values ('MQB-568', 'Hayes LLC');
insert into courses (code, name) values ('UWP-432', 'Breitenberg, Simonis and Batz');
insert into courses (code, name) values ('SIS-497', 'Sporer Inc');
insert into courses (code, name) values ('QXK-849', 'Lueilwitz, Johnson and Weimann');
insert into courses (code, name) values ('QPF-989', 'Wolf-Stark');
insert into courses (code, name) values ('RZC-624', 'Waelchi, McGlynn and Lynch');
insert into courses (code, name) values ('HYA-849', 'Lebsack, Ward and Ferry');
insert into courses (code, name) values ('FQI-876', 'Keeling and Sons');
insert into courses (code, name) values ('LUK-662', 'Barrows LLC');
insert into courses (code, name) values ('DPE-466', 'Hessel-Robel');
insert into courses (code, name) values ('PUN-894', 'Kub Inc');
insert into courses (code, name) values ('IGC-892', 'Botsford LLC');
insert into courses (code, name) values ('KXG-836', 'Koepp-Dare');
insert into courses (code, name) values ('IOZ-060', 'Hackett, O''Conner and Bernier');
insert into courses (code, name) values ('EBZ-093', 'Dare, Sporer and Rutherford');
insert into courses (code, name) values ('AKR-243', 'Rau-Reynolds');
insert into courses (code, name) values ('RTE-793', 'Johnston, Nikolaus and Fay');
insert into courses (code, name) values ('GSE-459', 'Mraz-Kohler');
insert into courses (code, name) values ('WCD-778', 'Bins Group');
insert into courses (code, name) values ('CXS-295', 'Stoltenberg, Wintheiser and Simonis');
insert into courses (code, name) values ('LZS-302', 'Green-Zemlak');
insert into courses (code, name) values ('GHS-242', 'Gutkowski-Cremin');
insert into courses (code, name) values ('ZHG-117', 'Morar Group');
insert into courses (code, name) values ('VLG-712', 'Hayes, Wolff and Davis');
insert into courses (code, name) values ('RCY-881', 'Considine, Brakus and Powlowski');
insert into courses (code, name) values ('XVP-594', 'Bayer-Morar');
insert into courses (code, name) values ('YWV-741', 'Kunde-Reynolds');
insert into courses (code, name) values ('KJW-273', 'King, Schinner and Larkin');
insert into courses (code, name) values ('BZM-950', 'Schiller Inc');
insert into courses (code, name) values ('FKJ-174', 'Dietrich LLC');
insert into courses (code, name) values ('EOX-338', 'Larkin-Dickinson');
insert into courses (code, name) values ('FOS-938', 'Murray Inc');
insert into courses (code, name) values ('KYQ-134', 'Ferry, Leffler and Collier');
insert into courses (code, name) values ('YJP-153', 'Johnston-Hamill');
insert into courses (code, name) values ('GUE-778', 'Stanton, Simonis and O''Reilly');
insert into courses (code, name) values ('IFE-576', 'Wilkinson-Lockman');
insert into courses (code, name) values ('WCM-142', 'Lesch and Sons');
insert into courses (code, name) values ('AZE-268', 'Hudson, Reilly and Reichel');
insert into courses (code, name) values ('ZSB-380', 'Huels and Sons');
insert into courses (code, name) values ('QPQ-072', 'Turcotte-Hegmann');
insert into courses (code, name) values ('UNU-345', 'Hessel-Zboncak');
insert into courses (code, name) values ('URJ-088', 'Mante, Tremblay and Reichel');
insert into courses (code, name) values ('UYX-656', 'Herman, Greenfelder and Cole');
insert into courses (code, name) values ('PGA-285', 'Boehm, Daugherty and Lehner');
insert into courses (code, name) values ('JMF-026', 'Muller Inc');
insert into courses (code, name) values ('AVS-978', 'Reinger LLC');
insert into courses (code, name) values ('VJA-686', 'Rolfson Inc');
insert into courses (code, name) values ('ZWP-850', 'Hartmann-Greenfelder');
insert into courses (code, name) values ('UBW-999', 'Fadel and Sons');
insert into courses (code, name) values ('LTY-083', 'Purdy and Sons');
insert into courses (code, name) values ('NDW-873', 'Hessel, Harber and Dooley');
insert into courses (code, name) values ('QWO-734', 'Hane, Lehner and Christiansen');
insert into courses (code, name) values ('TPW-357', 'Ritchie-D''Amore');
insert into courses (code, name) values ('DAX-623', 'Skiles, Larson and Runolfsson');
insert into courses (code, name) values ('WDB-614', 'Hoeger, Reynolds and Monahan');
insert into courses (code, name) values ('RKV-905', 'Konopelski-Fisher');
insert into courses (code, name) values ('QTC-597', 'Gerlach and Sons');
insert into courses (code, name) values ('NQI-059', 'Volkman-Wyman');
insert into courses (code, name) values ('LQR-925', 'Ankunding-Wisoky');
insert into courses (code, name) values ('FHC-270', 'Koepp Inc');
insert into courses (code, name) values ('VUP-333', 'Mitchell LLC');
insert into courses (code, name) values ('FGT-133', 'Bailey-Larson');
insert into courses (code, name) values ('OIY-715', 'Volkman-Kulas');
insert into courses (code, name) values ('ZZO-919', 'Kohler Inc');
insert into courses (code, name) values ('PXR-432', 'Huels-Cruickshank');
insert into courses (code, name) values ('MWI-063', 'Towne-Renner');
insert into courses (code, name) values ('XTL-978', 'Kirlin-Sporer');
insert into courses (code, name) values ('UDO-215', 'Friesen Inc');
insert into courses (code, name) values ('XCX-401', 'Hahn-Ortiz');
insert into courses (code, name) values ('LQX-135', 'Rice, Bartoletti and McGlynn');
insert into courses (code, name) values ('ZLR-628', 'Kessler-Streich');
insert into courses (code, name) values ('RYK-950', 'Boyer-Streich');
insert into courses (code, name) values ('CWC-788', 'Ferry, Lind and Kris');
insert into courses (code, name) values ('ATU-754', 'Thompson-Casper');
insert into courses (code, name) values ('GPA-514', 'Pacocha-Reichert');
insert into courses (code, name) values ('CLD-734', 'Batz, Jaskolski and Balistreri');
insert into courses (code, name) values ('XCN-904', 'Spinka, Ondricka and Herzog');
insert into courses (code, name) values ('HUO-277', 'Auer LLC');
insert into courses (code, name) values ('CWH-186', 'Koepp Group');
insert into courses (code, name) values ('LJH-128', 'Jenkins, Schmitt and Denesik');
insert into courses (code, name) values ('IQA-169', 'Fay and Sons');
insert into courses (code, name) values ('ZTE-942', 'Emmerich-Schumm');
insert into courses (code, name) values ('ZEF-567', 'Weimann, Hermiston and McDermott');
insert into courses (code, name) values ('GSV-592', 'Luettgen, Nikolaus and Carroll');
insert into courses (code, name) values ('HMU-129', 'Hauck Group');
insert into courses (code, name) values ('OSW-814', 'Bashirian, Bogisich and Schinner');
insert into courses (code, name) values ('DMJ-011', 'Von, Hoppe and Nader');
insert into courses (code, name) values ('EEV-127', 'Gibson LLC');
insert into courses (code, name) values ('WRE-365', 'Wehner and Sons');
insert into courses (code, name) values ('REJ-547', 'Harris, Kris and Hilpert');
insert into courses (code, name) values ('JPS-957', 'Monahan-Fadel');
insert into courses (code, name) values ('VIY-166', 'McGlynn-Larson');
insert into courses (code, name) values ('SUW-449', 'Torp-Marquardt');
insert into courses (code, name) values ('KNE-513', 'Hirthe Group');
insert into courses (code, name) values ('WBV-130', 'McKenzie-Klein');
insert into courses (code, name) values ('RSE-465', 'Heaney, McGlynn and Kshlerin');
insert into courses (code, name) values ('QPX-016', 'Larson-Becker');
insert into courses (code, name) values ('IFM-811', 'Block, Walker and Sipes');
insert into courses (code, name) values ('PWF-744', 'Harber-Rowe');
insert into courses (code, name) values ('UMC-415', 'Hahn-Schneider');
insert into courses (code, name) values ('SET-457', 'Kub-McClure');
insert into courses (code, name) values ('UYT-714', 'Pollich, Rodriguez and Kozey');
insert into courses (code, name) values ('UUN-559', 'Robel-Schinner');
insert into courses (code, name) values ('KCN-923', 'Kunde, Mayer and Lesch');
insert into courses (code, name) values ('POO-756', 'Fahey-Beatty');
insert into courses (code, name) values ('DIB-051', 'Crist LLC');
insert into courses (code, name) values ('JGH-517', 'Durgan-Daniel');
insert into courses (code, name) values ('OFO-907', 'Haley LLC');
insert into courses (code, name) values ('XZZ-889', 'Rutherford Group');
insert into courses (code, name) values ('IDP-779', 'Smitham Group');
insert into courses (code, name) values ('SPA-789', 'Fahey McClure');
insert into courses (code, name) values ('AKB-129', 'Harber Schumm');
insert into courses (code, name) values ('NPA-592', 'Fahey LLC');
