insert into departments (name, faculty_id) values ('Architecture', 1);
insert into departments (name, faculty_id) values ('Media Arts and Sciences', 1);
insert into departments (name, faculty_id) values ('Urban Studies and Planning', 1);
insert into departments (name, faculty_id) values ('Aeronautics and Astronautics', 2);
insert into departments (name, faculty_id) values ('Biological Engineering', 2);
insert into departments (name, faculty_id) values ('Chemical Engineering', 2);
insert into departments (name, faculty_id) values ('Civil and Environmental Engineering', 2);
insert into departments (name, faculty_id) values ('Electrical Engineering and Computer Science', 2);
insert into departments (name, faculty_id) values ('Computer Engineering', 2);
insert into departments (name, faculty_id) values ('Materials Science and Engineering', 2);
insert into departments (name, faculty_id) values ('Mechanical Engineering', 2);
insert into departments (name, faculty_id) values ('Medical Engineering and Science', 2);
insert into departments (name, faculty_id) values ('Nuclear Science and Engineering', 2);
insert into departments (name, faculty_id) values ('Anthropology', 3);
insert into departments (name, faculty_id) values ('Comparative Media Studies/Writing', 3);
insert into departments (name, faculty_id) values ('Economics', 3);
insert into departments (name, faculty_id) values ('Global Languages', 3);
insert into departments (name, faculty_id) values ('History', 3);
insert into departments (name, faculty_id) values ('Humanities', 3);
insert into departments (name, faculty_id) values ('Humanities + Engineering/Science', 3);
insert into departments (name, faculty_id) values ('Linguistics', 3);
insert into departments (name, faculty_id) values ('Literature', 3);
insert into departments (name, faculty_id) values ('Music and Theater Arts', 3);
insert into departments (name, faculty_id) values ('Philosophy', 3);
insert into departments (name, faculty_id) values ('Political Science', 3);
insert into departments (name, faculty_id) values ('Science, Technology, and Society', 3);
insert into departments (name, faculty_id) values ('Management', 4);
insert into departments (name, faculty_id) values ('Biology', 5);
insert into departments (name, faculty_id) values ('Brain and Cognitive Sciences', 5);
insert into departments (name, faculty_id) values ('Chemistry', 5);
insert into departments (name, faculty_id) values ('Earth, Atmospheric, and Planetary Sciences', 5);
insert into departments (name, faculty_id) values ('Mathematics', 5);
insert into departments (name, faculty_id) values ('Physics', 5);
insert into departments (name, faculty_id) values ('Data, Systems, and Society', 6);
insert into departments (name, faculty_id) values ('Electrical Engineering and Computer Science', 6);
