insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Tadeo', 'Brandea', 'Whebell', '!!!!!!!!!!!', 'bwhebell0@arizona.edu', '1994-06-22');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Ashbey', 'Carolynn', 'McGuigan', '!!!!!!!!!!!', 'cmcguigan1@businessinsider.com', '1994-04-08');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Marietta', 'Zondra', 'Battin', '!!!!!!!!!!!', 'zbattin2@marketwatch.com', '1994-04-19');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Nobe', 'Kessia', 'Forrest', '!!!!!!!!!!!', 'kforrest3@desdev.cn', '1994-06-05');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Maddy', 'Camilla', 'MacGown', '!!!!!!!!!!!', 'cmacgown4@weibo.com', '1994-02-18');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Berrie', 'Courtnay', 'Laurisch', '!!!!!!!!!!!', 'claurisch5@i2i.jp', '1994-12-21');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Suki', 'Nessa', 'Whymark', '!!!!!!!!!!!', 'nwhymark6@netvibes.com', '1994-12-13');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Shaylynn', 'Renard', 'Earingey', '!!!!!!!!!!!', 'rearingey7@icq.com', '1994-09-21');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Evered', 'Seward', 'Spottswood', '!!!!!!!!!!!', 'sspottswood8@abc.net.au', '1994-08-03');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Cloris', 'Jan', 'Mellsop', '!!!!!!!!!!!', 'jmellsop9@moonfruit.com', '1994-09-11');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Rudolf', 'Alaine', 'Earpe', '!!!!!!!!!!!', 'aearpea@a8.net', '1994-09-01');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Bethany', 'Geno', 'Jovicic', '!!!!!!!!!!!', 'gjovicicb@auda.org.au', '1994-09-22');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Yovonnda', 'Kliment', 'Eye', '!!!!!!!!!!!', 'keyec@microsoft.com', '1994-08-28');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Barrie', 'Nathanil', 'Coenraets', '!!!!!!!!!!!', 'ncoenraetsd@tripod.com', '1994-11-21');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Cass', 'Vite', 'Warton', '!!!!!!!!!!!', 'vwartone@google.it', '1994-09-29');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Francois', 'Barri', 'Nuscha', '!!!!!!!!!!!', 'bnuschaf@vkontakte.ru', '1994-05-02');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Dewie', 'Buddy', 'Padell', '!!!!!!!!!!!', 'bpadellg@yolasite.com', '1994-11-23');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Mirna', 'Reynard', 'Naris', '!!!!!!!!!!!', 'rnarish@ycombinator.com', '1994-10-08');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Normie', 'Annadiane', 'Stot', '!!!!!!!!!!!', 'astoti@istockphoto.com', '1994-04-12');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Griffin', 'Godwin', 'Dorey', '!!!!!!!!!!!', 'gdoreyj@scribd.com', '1994-08-23');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Buiron', 'Etan', 'Beinke', '!!!!!!!!!!!', 'ebeinkek@java.com', '1994-04-24');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Duffy', 'Fabien', 'Fewell', '!!!!!!!!!!!', 'ffewelll@privacy.gov.au', '1994-09-07');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Jinny', 'Eugenie', 'Ort', '!!!!!!!!!!!', 'eortm@symantec.com', '1994-06-07');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Charles', 'Cobb', 'Wooderson', '!!!!!!!!!!!', 'cwoodersonn@cnn.com', '1994-03-10');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Poul', 'Lorette', 'Holton', '!!!!!!!!!!!', 'lholtono@gizmodo.com', '1994-03-25');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Sindee', 'Claudio', 'Ponter', '!!!!!!!!!!!', 'cponterp@cdbaby.com', '1994-06-19');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Erek', 'Stanfield', 'Tilzey', '!!!!!!!!!!!', 'stilzeyq@umich.edu', '1994-08-17');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Dee', 'Linnea', 'Ledekker', '!!!!!!!!!!!', 'lledekkerr@buzzfeed.com', '1994-06-14');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Elysia', 'Aloise', 'Smullen', '!!!!!!!!!!!', 'asmullens@github.com', '1994-07-13');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Jeanette', 'Craggie', 'Stanluck', '!!!!!!!!!!!', 'cstanluckt@purevolume.com', '1994-04-21');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Evelyn', 'Drona', 'Stutely', '!!!!!!!!!!!', 'dstutelyu@amazon.de', '1994-12-31');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Sadie', 'Cariotta', 'Wollard', '!!!!!!!!!!!', 'cwollardv@lycos.com', '1994-07-21');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Jacinda', 'Giffard', 'Wong', '!!!!!!!!!!!', 'gwongw@eepurl.com', '1994-11-12');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Dimitry', 'Minni', 'Hateley', '!!!!!!!!!!!', 'mhateleyx@wp.com', '1994-03-11');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Chrisy', 'Pavel', 'Kilmurry', '!!!!!!!!!!!', 'pkilmurryy@marketwatch.com', '1994-04-19');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Janeczka', 'Humfrid', 'Ellens', '!!!!!!!!!!!', 'hellensz@amazon.de', '1994-11-17');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Baxter', 'Mathian', 'Staples', '!!!!!!!!!!!', 'mstaples10@vkontakte.ru', '1994-03-31');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Althea', 'Charlene', 'Bogges', '!!!!!!!!!!!', 'cbogges11@edublogs.org', '1994-06-27');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Carry', 'Audy', 'Dopson', '!!!!!!!!!!!', 'adopson12@soup.io', '1994-09-13');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Mick', 'Leeland', 'Summerlad', '!!!!!!!!!!!', 'lsummerlad13@yellowpages.com', '1994-02-14');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Sheila', 'Jessamine', 'Mordie', '!!!!!!!!!!!', 'jmordie14@va.gov', '1994-05-11');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Roz', 'Kylen', 'Fundell', '!!!!!!!!!!!', 'kfundell15@php.net', '1994-01-21');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Gabbie', 'Aurelie', 'Brahams', '!!!!!!!!!!!', 'abrahams16@rambler.ru', '1994-02-01');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Teodoro', 'Cris', 'Dargavel', '!!!!!!!!!!!', 'cdargavel17@spotify.com', '1994-06-24');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Robyn', 'Kurtis', 'Proby', '!!!!!!!!!!!', 'kproby18@berkeley.edu', '1994-05-21');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Ned', 'Cookie', 'Havill', '!!!!!!!!!!!', 'chavill19@nsw.gov.au', '1994-04-10');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Melina', 'Rebekkah', 'Legh', '!!!!!!!!!!!', 'rlegh1a@woothemes.com', '1994-08-10');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Scarface', 'Base', 'Howland', '!!!!!!!!!!!', 'bhowland1b@edublogs.org', '1994-01-26');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Bethina', 'Joanie', 'Ugolini', '!!!!!!!!!!!', 'jugolini1c@webmd.com', '1994-04-16');
insert into lecturers (first_name, middle_name, last_name, citizen_id, email, birth_date) values ('Valentina', 'Emmalynn', 'Brightling', '!!!!!!!!!!!', 'ebrightling1d@nytimes.com', '1994-03-01');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Adrea', 'Bailie', '!!!!!!!!!!!', 'abailie0@army.mil', '1994-05-06');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Lane', 'MacCafferty', '!!!!!!!!!!!', 'lmaccafferty1@storify.com', '1994-08-29');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Maryjane', 'Gritskov', '!!!!!!!!!!!', 'mgritskov2@hc360.com', '1994-07-07');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Reg', 'Destouche', '!!!!!!!!!!!', 'rdestouche3@rediff.com', '1994-04-26');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Jefferson', 'Arnaut', '!!!!!!!!!!!', 'jarnaut4@bizjournals.com', '1994-03-22');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Dasya', 'Dabinett', '!!!!!!!!!!!', 'ddabinett5@ox.ac.uk', '1994-01-17');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Katya', 'Shrive', '!!!!!!!!!!!', 'kshrive6@fastcompany.com', '1994-02-11');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Torey', 'Blaydon', '!!!!!!!!!!!', 'tblaydon7@latimes.com', '1994-04-14');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Ferguson', 'Coleyshaw', '!!!!!!!!!!!', 'fcoleyshaw8@forbes.com', '1994-10-24');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Nevsa', 'Coultard', '!!!!!!!!!!!', 'ncoultard9@homestead.com', '1994-01-27');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Grace', 'Shires', '!!!!!!!!!!!', 'gshiresa@netscape.com', '1994-12-14');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Darcie', 'Bagehot', '!!!!!!!!!!!', 'dbagehotb@smh.com.au', '1994-04-07');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Reinhold', 'Honywill', '!!!!!!!!!!!', 'rhonywillc@cafepress.com', '1994-02-17');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Reginauld', 'Antonovic', '!!!!!!!!!!!', 'rantonovicd@stumbleupon.com', '1994-11-22');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Sybil', 'Howatt', '!!!!!!!!!!!', 'showatte@marriott.com', '1994-01-18');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Ceciley', 'Dimond', '!!!!!!!!!!!', 'cdimondf@pagesperso-orange.fr', '1994-12-05');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Adelina', 'Pordal', '!!!!!!!!!!!', 'apordalg@jimdo.com', '1994-12-01');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Deidre', 'Szymonwicz', '!!!!!!!!!!!', 'dszymonwiczh@weebly.com', '1994-05-15');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Darleen', 'Stear', '!!!!!!!!!!!', 'dsteari@odnoklassniki.ru', '1994-06-26');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Trudey', 'Duckinfield', '!!!!!!!!!!!', 'tduckinfieldj@techcrunch.com', '1994-12-23');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Casie', 'Fountain', '!!!!!!!!!!!', 'cfountaink@istockphoto.com', '1994-01-20');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Slade', 'Bachelor', '!!!!!!!!!!!', 'sbachelorl@jimdo.com', '1994-12-02');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Cecily', 'Zuann', '!!!!!!!!!!!', 'czuannm@businesswire.com', '1994-04-28');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Paolina', 'Jodrellec', '!!!!!!!!!!!', 'pjodrellecn@telegraph.co.uk', '1994-06-12');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Grannie', 'Simonutti', '!!!!!!!!!!!', 'gsimonuttio@cyberchimps.com', '1994-04-19');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Pablo', 'McGavin', '!!!!!!!!!!!', 'pmcgavinp@lulu.com', '1994-12-21');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Jenelle', 'Tunnow', '!!!!!!!!!!!', 'jtunnowq@jugem.jp', '1994-01-19');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Cassius', 'Priestman', '!!!!!!!!!!!', 'cpriestmanr@liveinternet.ru', '1994-03-16');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Helen-elizabeth', 'Bugden', '!!!!!!!!!!!', 'hbugdens@buzzfeed.com', '1994-08-30');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Quill', 'Dallmann', '!!!!!!!!!!!', 'qdallmannt@spotify.com', '1994-07-21');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Trip', 'Pretious', '!!!!!!!!!!!', 'tpretiousu@linkedin.com', '1994-06-06');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Evanne', 'Stanbury', '!!!!!!!!!!!', 'estanburyv@pen.io', '1994-04-17');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Rosella', 'Kail', '!!!!!!!!!!!', 'rkailw@theatlantic.com', '1994-10-25');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Kiri', 'Saby', '!!!!!!!!!!!', 'ksabyx@w3.org', '1994-12-24');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Gay', 'Copyn', '!!!!!!!!!!!', 'gcopyny@wsj.com', '1994-03-24');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Giraud', 'Sussems', '!!!!!!!!!!!', 'gsussemsz@sun.com', '1994-11-25');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Kaycee', 'Hounsham', '!!!!!!!!!!!', 'khounsham10@yahoo.com', '1994-05-16');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Lucio', 'Althrope', '!!!!!!!!!!!', 'lalthrope11@elegantthemes.com', '1994-09-21');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Allyson', 'Edwinson', '!!!!!!!!!!!', 'aedwinson12@biblegateway.com', '1994-03-25');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Selby', 'Ratie', '!!!!!!!!!!!', 'sratie13@tripod.com', '1994-07-01');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Roseann', 'Yeeles', '!!!!!!!!!!!', 'ryeeles14@myspace.com', '1994-11-24');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Rubia', 'Stanning', '!!!!!!!!!!!', 'rstanning15@ask.com', '1994-04-26');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Adiana', 'Leddie', '!!!!!!!!!!!', 'aleddie16@geocities.jp', '1994-09-24');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Saxon', 'Wake', '!!!!!!!!!!!', 'swake17@usa.gov', '1994-02-24');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Brittany', 'Botterill', '!!!!!!!!!!!', 'bbotterill18@wikispaces.com', '1994-04-02');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Ferdie', 'Scrymgeour', '!!!!!!!!!!!', 'fscrymgeour19@prweb.com', '1994-10-15');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Moses', 'Sleigh', '!!!!!!!!!!!', 'msleigh1a@paypal.com', '1994-01-17');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Berny', 'Riggeard', '!!!!!!!!!!!', 'briggeard1b@last.fm', '1994-03-21');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Daniela', 'Luttger', '!!!!!!!!!!!', 'dluttger1c@multiply.com', '1994-12-16');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Barbette', 'Wybrew', '!!!!!!!!!!!', 'bwybrew1d@reuters.com', '1994-12-07');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Pebrook', 'Fenny', '!!!!!!!!!!!', 'pfenny1e@ted.com', '1994-03-28');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Bearnard', 'Rosellini', '!!!!!!!!!!!', 'brosellini1f@diigo.com', '1994-08-14');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Earvin', 'Godspede', '!!!!!!!!!!!', 'egodspede1g@weather.com', '1994-08-16');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Gena', 'Millberg', '!!!!!!!!!!!', 'gmillberg1h@123-reg.co.uk', '1994-08-20');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Idell', 'Yeatman', '!!!!!!!!!!!', 'iyeatman1i@desdev.cn', '1994-08-15');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Nevil', 'Shurrock', '!!!!!!!!!!!', 'nshurrock1j@fotki.com', '1994-06-18');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Donella', 'Crosskill', '!!!!!!!!!!!', 'dcrosskill1k@facebook.com', '1994-01-27');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Jecho', 'Elcom', '!!!!!!!!!!!', 'jelcom1l@sogou.com', '1994-05-14');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Kaylee', 'Dibson', '!!!!!!!!!!!', 'kdibson1m@hubpages.com', '1994-09-05');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Gilberto', 'Ostridge', '!!!!!!!!!!!', 'gostridge1n@dailymotion.com', '1994-06-29');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Melvyn', 'Dilks', '!!!!!!!!!!!', 'mdilks1o@nbcnews.com', '1994-01-27');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Tracie', 'Silversmidt', '!!!!!!!!!!!', 'tsilversmidt1p@topsy.com', '1994-11-10');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Chiquia', 'Mc Trusty', '!!!!!!!!!!!', 'cmctrusty1q@youtu.be', '1994-12-06');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Else', 'Kellard', '!!!!!!!!!!!', 'ekellard1r@1688.com', '1994-08-30');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Claudelle', 'Rive', '!!!!!!!!!!!', 'crive1s@usda.gov', '1994-11-16');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Jane', 'Klimushev', '!!!!!!!!!!!', 'jklimushev1t@1und1.de', '1994-11-13');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Hyacinth', 'Comellini', '!!!!!!!!!!!', 'hcomellini1u@vk.com', '1994-06-01');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Towny', 'Emslie', '!!!!!!!!!!!', 'temslie1v@gmpg.org', '1994-12-02');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Guillemette', 'Tidbold', '!!!!!!!!!!!', 'gtidbold1w@discuz.net', '1994-02-06');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Neils', 'Altoft', '!!!!!!!!!!!', 'naltoft1x@oracle.com', '1994-09-24');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Frank', 'Melpuss', '!!!!!!!!!!!', 'fmelpuss1y@wiley.com', '1994-12-20');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Obadias', 'Hadlington', '!!!!!!!!!!!', 'ohadlington1z@wired.com', '1994-08-06');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Kippar', 'Gallard', '!!!!!!!!!!!', 'kgallard20@tripadvisor.com', '1994-10-28');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Freddy', 'Hourihane', '!!!!!!!!!!!', 'fhourihane21@histats.com', '1994-01-25');
insert into lecturers (first_name, last_name, citizen_id, email, birth_date) values ('Theadora', 'Pomfrett', '!!!!!!!!!!!', 'tpomfrett22@facebook.com', '1994-12-11');
